# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Постер')),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Год выхода')),
                ('kp_rating', models.FloatField(blank=True, verbose_name='Оценка на кинопоиске')),
                ('description', models.TextField(blank=True, verbose_name='Описание на кинопоиске')),
                ('man_rating', models.FloatField(blank=True, verbose_name='Мужская оценка')),
                ('woman_rating', models.FloatField(blank=True, verbose_name='Женская оценка')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Сущность',
                'verbose_name_plural': 'Сущности',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='item.Tag', verbose_name='Теги'),
        ),
    ]
